### ISSUE TITLE
dir must be a subdirectory of stop

### ISSUE THREAD

**Issue by asimashfaq** [christian-hackyourshack/npm#63]
I am unable to run i am getting this error

dir must be a subdirectory of stop
 error   dir must be a subdirectory of stop
  File:
    /Users/qasimkhokhar/0x-equity-v2/apps/frontend/src/content/test.mdx
  Stacktrace:
Error: dir must be a subdirectory of stop
    at mergeFrontmatter (file:///Users/qasimkhokhar/0x-equity-v2/node_modules/astro-m2dx/dist/index.js:541:11)
    at transformer (file:///Users/qasimkhokhar/0x-equity-v2/node_modules/astro-m2dx/dist/index.js:931:28)

**Comment by asimashfaq** [comment]
Seems like some version issue
