### ISSUE TITLE
 dir must be a subdirectory of stop 

### ISSUE THREAD

**Issue by ispringle** [christian-hackyourshack/npm#64]
Just trying out this plugin today. It worked fine until I added either the `autoImport` or `exportComponents` feature, then I started getting the error:

```
 error   'dir' must be a subdirectory of 'stop'
  File:
    /Users/IPringle/git/hub/ispringle/sylvan/content/about.mdx:55:25
  Stacktrace:
Error: 'dir' must be a subdirectory of 'stop'
    at findUpAll (file:///Users/IPringle/git/hub/ispringle/sylvan/node_modules/astro-m2dx/dist/index.js:66:13)
    at transformer (file:///Users/IPringle/git/hub/ispringle/sylvan/node_modules/astro-m2dx/dist/index.js:956:36)
```

If I disable both features then it works again.

**Comment by christian-hackyourshack** [comment]
Thanks for the hint. I will look into it tonight. From your path it looks, like you are on Linux (or similar, e.g. WSL). Another user reported that before on Windows, but I could not reproduce it on my side. Can you please share your configuration or some snippets of it? Thanks in advance.

**Comment by ispringle** [comment]
This is on a Mac, however I'm also getting the error on an Ubuntu docker container. For all intents and purposes, Mac and Linux filesystems are identical at the high level Node is working at -- or at least that's been my experience.

**Comment by ispringle** [comment]
Figured out the issue. m2dx assumes that the content directory is a subdirectory of the `src` directory. 

I tried moving the content dir from the project root to the ./src dir and this sort of worked, however it did not work for the index files so I still got the error if I visited an index page.

**Comment by christian-hackyourshack** [comment]
Sorry, this takes so long on my side right now, I hope you found your way around these. Just wanted to quickly let you know, that I won't find the time to further investigate this for the next two weeks, as we will launch our new site soon. Promise, It's not forgotten though.

**Comment by amurashincertinia** [comment]
Hello there!

I've got the same issue: the plugin assumes that the source directory is `./src`, so if `srcDir` in `astro.config.js` is set to anything other than the default, the plugin errors.

Steps to recreate:
1. In an existing Astro project, rename `src` directory to `source`.
2. Edit `astro.config.js` and configure `srcDir: './source'`.
3. Run `astro build`.

Expected result:
Build successful.

Actual result:
```
Error: Failed to parse Markdown file "[...]/source/pages/index.md":
dir must be a subdirectory of stop
    at mergeFrontmatter (file://[...]/node_modules/astro-m2dx/dist/index.js:542:11)
    at transformer (file://[...]/node_modules/astro-m2dx/dist/index.js:932:28)
```
